### ISSUE TITLE
Ara Yaghsizian, Matthew Connors, Sandy Pok ---- Project 3 Food By Mood!!!

### ISSUE THREAD

**Issue by MurphyPicard** [ga-wdi-pvd/project3-gallery#5]
Front End: 

https://github.com/mconnors333/food-by-mood-ui

Back End: 

https://github.com/mconnors333/food-by-mood-api

**Comment by estermer** [comment]
Scoring 0 - 3
Your Group Score:  2 

Matt, Ara, and Sandy,

Great job with this project. Your code was neat, you met the minimum requirements, you implemented full crud and more. Your design was lacking a little but unique and well organized for the short period of time you had to develop. 

I am happy you put together a readme to help on viewers understand your application more. 

Your code was neat and well put together. Clean.

Here are some fixes. In your front end repo, just get a screen shot of your trello board and draw.io's erd and models. I cannot access these and they are not going to visible to future emplyers, so just provide a screen shot.

Also in this repo, Add a list of contributors with links to each of your repos. This will help viewers trace who everyone is.

In referring to the technologies. Refer to AJAX rather than HTTP. HTTP is the protocol but AJAX stands out more in terms of a technology rather that a protocol.

One other thing to focus on, when I was trying out your app I made a new food in a mood called pizza and thn when I viewed it, it didn't show the pizza I created, it showed one that was previously made. Looking into this farther, I notices you search which one to show based on the `:title` of the food. This is ok, but it makes more sense to search by `_id` because it will grab the unique version of data if there exists multiple versions of the same thing that has the same title.

Other than these critics, your application was great for your first MEAN Stack app and your first Group project.

Keep up the good work!

-Eric
